services:
  # Floraccess App Web #
  floraccess-app-web:
    image: nginx:stable-alpine
    working_dir: /app
    env_file:
      - ./.env
    networks:
      - flower-garden-net
    ports:
      - ${APP_PORT:-}:80
    depends_on:
      floraccess-server:
        condition: service_healthy
    volumes:
      - ./build/web:/usr/share/nginx/html/
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./.env:/usr/share/nginx/html/assets/.env:ro
    command: ["nginx", "-g", "daemon off;"]
    environment:
      - FLUTTER_ENV=dev