name: build and publish Docker images

on:
  push:
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set lowercase repository owner
        id: repo_owner_lc
        run: echo "repo_owner_lc=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_OUTPUT

      - name: Get app version from pubspec
        id: vars
        run: |
          version=$(grep '^version:' pubspec.yaml | head -n1 | sed -E 's/^version:[[:space:]]*([0-9]+\.[0-9]+\.[0-9]+).*$/\1/')
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Connexion à Docker Hub (si credentials présents)
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # Connexion à GitHub Container Registry
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # --- Docker Hub Builds ---
      - name: Build and push floraccess-app-web (Docker Hub)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/floraccess-app-web:${{ steps.vars.outputs.version }}
            ${{ secrets.DOCKERHUB_USERNAME }}/floraccess-app-web:latest

      # --- GHCR Builds ---
      - name: Build and push floraccess-app-web (GHCR)
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/${{ steps.repo_owner_lc.outputs.repo_owner_lc }}/floraccess-app-web:${{ steps.vars.outputs.version }}
            ghcr.io/${{ steps.repo_owner_lc.outputs.repo_owner_lc }}/floraccess-app-web:latest
