name: Create GitHub Release

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Get app version from pubspec
        id: vars
        run: |
          version=$(grep '^version:' pubspec.yaml | head -n1 | sed -E 's/^version:[[:space:]]*([0-9]+\.[0-9]+\.[0-9]+).*$/\1/')
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Format repository name
        id: repo_name
        run: |
          repo="${GITHUB_REPOSITORY}"
          # On enlève le propriétaire
          repo_name="${repo#*/}"
          # On remplace les underscores par des espaces
          repo_name="${repo_name//_/ }"
          echo "name=$repo_name" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ steps.vars.outputs.version }}
          name: "${{ steps.repo_name.outputs.name }} v${{ steps.vars.outputs.version }}"
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
